name: github-infrastructure
run-name: Deploy all github-infrastructure
on:
  push:
    branches: [main]
permissions:
  actions: write
  attestations: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
env:
  TF_BACKEND_GIT_HTTP_USERNAME: user
  TF_BACKEND_GIT_HTTP_PASSWORD: pswd
jobs:
  gitlab-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: plumber-cd/setup-terraform-backend-git@v1
      - run: |
          cd ${{ github.workspace }}
          terraform-backend-git &
          terraform version
          terraform init
          terraform apply -auto-approve
