name: tf-apply
on: [push]
jobs:
  tf-apply:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: checkout-repo
        uses: actions/checkout@v4
      - name: setup-terraform-backend
        uses: plumber-cd/setup-terraform-backend-git@v1
      - name: tf-apply
        run: |
          cd ${{ github.workspace }}
          terraform-backend-git 2>/dev/null &
          terraform init
          terraform apply -auto-approve
